### PR TITLE
Attempt to fix R builder when there is a vignette; some doc updates

### PR DESCRIPTION
**Pull request by nealrichardson**
See https://github.com/apache/arrow/pull/5279#issuecomment-530026718.

### CODE REVIEW

**Comment by kszucs** [comment]
@nealrichardson we were discussing that there is some redundancy in the builder steps. If you can recall it then we should remove that to get better build times.

**Comment by kszucs** [comment]
@nealrichardson we were discussing that there is some redundancy in the builder steps. If you can recall it then we should remove that to get better build times.

**Comment by nealrichardson** [comment]
I removed that in this PR already.

**Comment by kszucs** [comment]
Ohh, so the install was it! Then it looks good to me. The travis builds are redundant with the azure ones, so everything is green.

**Comment by nealrichardson** [comment]
I don't see that it ran the Ubuntu R builder.

**Comment by kszucs** [comment]
Indeed, that is missing from the azure-pipelines.yaml

**Pull request merged**
